### ISSUE TITLE
Get authorization token for notebooks API

### ISSUE THREAD

**Issue by l1ghtspeed** [GoogleCloudPlatform/jupyter-extensions#110]

**Comment by prodonjs** [comment]
Following the example from https://docs.google.com/document/d/1ebXl7PjjVg_9FugPzIgy_5K49fkRN8-2hoo_OaEIf6c, develop a standalone web application that can handle the OAuth 2.0 authentication flow for a user.

This page can be loaded from an IFrame or popup initiated from within the JupyterLab code. After the user authorizes the site to access GCP on their behalf, the access token can then be passed back to the JupyterLab page via the postMessage API.
