### ISSUE TITLE
Add CAIP logo to extension

### ISSUE THREAD

**Issue by yaminahq** [GoogleCloudPlatform/jupyter-extensions#209]
Look into the best place to put [this logo](https://lh3.googleusercontent.com/jXKgFfRZMYEO2Dl81SENWsvj0crnYUmR-8H7UFiHwPxI5BfIJjN23xVeUOdL4IZMu0oO38zE59AM=e14-rj-sc0xffffff-w1270) in the extension.

**Comment by prodonjs** [comment]
Closed by #288
