### ISSUE TITLE
Automatically close scaling dialog after operations complete

### ISSUE THREAD

**Issue by yaminahq** [GoogleCloudPlatform/jupyter-extensions#210]
After the reshaping operations complete show the dialog for a limited amount of time and then automatically close it. We can display a snackbar temporarily after it closes. However, one potential issue with this is if a user completes the reshaping request but doesn't see the snackbar they won't know if the operations were successful or not.

**Comment by prodonjs** [comment]
This is obsolete based on changes we made to show the new configuration but still require the user to close the dialog.
