### ISSUE TITLE
Explore charting libraries for resource utilization graphs

### ISSUE THREAD

**Issue by prodonjs** [GoogleCloudPlatform/jupyter-extensions#22]
[Design doc section](https://docs.google.com/document/d/1f6cb_fQVHcDq-0swoXpc4pwa-YRsjQtMjSiUcRyGfjg/edit#heading=h.11y9mrce9j04)

[Mock behavior](https://docs.google.com/presentation/d/1bPcRicop1_nr2Pxw5mITPyJEiDE8WLq8lyoiDfOTvJw/edit#slide=id.g8514ccd791_4_70)

**Comment by l1ghtspeed** [comment]
Research can be found at go/jupyter-extension-graphs
